### ISSUE TITLE
Execution Error when calling signFelt

### ISSUE THREAD

**Issue by gergold** [Zondax/ledger-starkware#7]
When I try this:
```
const MESSAGE_HASH = Buffer.alloc(32, 0xA0);
const PATH = "m/2645'/579218131'/0'/0'";

const signature = await app.signFelt(PATH, MESSAGE_HASH);
```
I get this error message:
```
{ returnCode: 25600, errorMessage: 'Execution Error', hash: undefined }
```

I was looking at the [unit test](https://github.com/Zondax/ledger-starkware/blob/f0766d0f7c2b6fd6387f878637dfa19c8277e6fa/zemu/tests/standard.test.ts#L136) to check what could be wrong and I noticed `data.felt` is defined as `Buffer.alloc(0xA0, 32)` where the two parameters seem inverted (should be `Buffer.alloc(size, fill)`). I was wondering if that unit test actually works.

**Comment by becominginsane** [comment]
Unfortunately the ledger emulator (speculos) doesn't support the stark curve so testing has to be done manually.
I'll get to debugging this error, but I suspect it's due to the new DER to RSV converter.
